<?php

namespace App\Models;

use App\Model;
use App\StorageInterface;

class User extends Model
{
    protected $table = 'users';

    public function __set($name, $value)
    {
        if ($name === 'password') {
            $value = $this->handlePassword($value);
        }
        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    public function checkPassword($login, $password)
    {
        $user = $this->storage->findWhere($this->table, ['login' => $login]);
        if (empty($user)) {
            return false;
        }

        return password_verify($user->solt . $password . $user->solt, $user->password);
    }

    protected function handlePassword($password)
    {
        $this->salt = rand(6, 10);

        return md5($this->salt . $password . $this->salt);
    }
}
