<?php

namespace App\Models;

use App\Model;
use App\StorageInterface;

class User extends Model
{
    protected $table = 'user';

    public function __set($name, $value)
    {
        if ($name === 'password') {
            $value = $this->handlePassword($value);
        }
        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    public function checkPassword($login, $password)
    {
        $user = $this->storage->findWhere($this->table, ['login' => $login]);
        if (empty($user)) {
            return false;
        }

        return password_verify($user->solt . $password . $user->solt, $user->password);
    }

    public function authenticate(bool $remember)
    {
        $this->token = rand(10000000000000000, 100000000000000000);
        $_SESSION['user']['token'] = $this->token;
        if ($remember) {
            $time = time()+86400 * 30 * 12;
            setcookie('loginUser', $this->login, $time);
            setcookie('tokenUser', $this->token, $time);
        }
    }

    public function unlog()
    {
        $this->token = null;
        $this->save();
    }

    protected function handlePassword($password)
    {
        $this->salt = rand(100000, 10000000);

        return md5($this->salt . $password . $this->salt);
    }


}
